export * from './antecedent'
export * from './array-concat-identity'
export * from './bigint-additive-identity'
export * from './num-add-identity'
export * from './num-mult-identity'
export * from './object-intersection-identity'
export * from './string-concat-identity'
