export * from './antecedent'
export * from './array-concat-identity'
export * from './bigint-add-identity'
export * from './bigint-mult-identity'
export * from './num-add-identity'
export * from './num-mult-identity'
export * from './object-assign-identity'
export * from './string-concat-identity'
